apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: willsapp
  namespace: argocd
  labels:
    app: willsapp
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/MrOnimus/rdremora.git
    targetRevision: HEAD
    path: k3s
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
